= SD Library for Arduino =

image:https://img.shields.io/github/release/mcci-catena/SD.svg["GitHub release", link="https://github.com/mcci-catena/SD/releases/latest"]
image:https://img.shields.io/github/commits-since/mcci-catena/SD/latest.svg["GitHub commits", link="https://github.com/mcci-catena/SD/compare/v1.3.0..master"]
image:https://travis-ci.com/mcci-catena/SD.svg?branch=master["Build Status", link="https://travis-ci.com/mcci-catena/SD"]

The SD library allows for reading from and writing to SD cards.

For more information about this library please visit the upstream reference pages at
http://www.arduino.cc/en/Reference/SD, or find this library on github at https://github.com/mcci-catena/SD.

This MCCI-Catena version is modified by MCCI to support SD cards attached on a different SPI bus (without doing compile-time `#define` magic). A new overload of `card.init()` requires a `SPIClass *` first parameter. For backward compatibility, all the older overloads of `card.init()` pass a default value of `SDCARD_SPI` to the low-level `::init()` method. On most platforms, `SDCARD_SPI` is `SPI`, but some platforms like the Arduino mkrzero override this; for compatibility, the definition of SDCARD_SPI must be hidden in `src/utility/Sd2Card.cpp`.

Although there's lots of code for other approaches, this fork of the driver only supports SPIClass-style interfaces.

IMPORTANT:	This library is licensed under GPL3. Thus, use of this library in your program effectively applies the terms of GPL3 to your entire program, not just this library!

== License ==

 Copyright (C) 2009 by William Greiman
 Copyright (C) 2010 SparkFun Electronics
 Copyright (C) 2019 MCCI Corporation

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a link:LICENSE.md[copy] of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
